// Ephemeral test-profile factory.
//
// gjoa doesn't need a per-profile chrome/ copy the way palefox did —
// chrome JS gets loaded by gjoa's built-in loader from
// <install_root>/gjoa-dev/, not from the profile. So all we need is
// a fresh profile dir with a user.js that enables Marionette and
// silences interruptions.

import { mkdtemp, writeFile, rm } from "node:fs/promises";
import { join } from "node:path";
import { tmpdir } from "node:os";

export interface TestProfile {
  /** Absolute path to the ephemeral profile directory. */
  path: string;
  /** Removes the profile directory. Call from a finally block. */
  cleanup(): Promise<void>;
}

const DEFAULT_USER_JS = `// Generated by tools/test-driver — DO NOT EDIT.
// Marionette
user_pref("marionette.port", 2828);
user_pref("marionette.enabled", true);
// No update / first-run / what's-new interruptions
user_pref("app.update.enabled", false);
user_pref("app.update.auto", false);
user_pref("app.update.silent", false);
user_pref("app.update.checkInstallTime", false);
user_pref("browser.startup.homepage_override.mstone", "ignore");
user_pref("browser.shell.checkDefaultBrowser", false);
user_pref("browser.startup.homepage", "about:blank");
user_pref("startup.homepage_welcome_url", "");
user_pref("startup.homepage_welcome_url.additional", "");
user_pref("startup.homepage_override_url", "");
user_pref("browser.tabs.warnOnClose", false);
user_pref("browser.tabs.warnOnCloseOtherTabs", false);
// Restore previous session — needed for tree-reconciliation tests
user_pref("browser.startup.page", 3);
user_pref("browser.sessionstore.resume_from_crash", true);
user_pref("toolkit.startup.max_resumed_crashes", -1);
// Vertical tabs on (gjoa-tabs default territory)
user_pref("sidebar.verticalTabs", true);
user_pref("sidebar.revamp", true);
// Telemetry off
user_pref("toolkit.telemetry.enabled", false);
user_pref("toolkit.telemetry.unified", false);
user_pref("datareporting.policy.dataSubmissionEnabled", false);
user_pref("datareporting.healthreport.uploadEnabled", false);
// Gjoa-tabs internal prefs (port kept the gjoa.* namespace)
user_pref("gjoa.debug", true);
// Exposes window.gjoaTest = { vim, state, history, … } so integration
// tests can drive the chrome layer past public surfaces.
user_pref("gjoa.test.exposeAPI", true);
`;

export async function createProfile(opts: { extraPrefs?: string } = {}): Promise<TestProfile> {
  const path = await mkdtemp(join(tmpdir(), "gjoa-test-"));
  const userJs = DEFAULT_USER_JS + (opts.extraPrefs ?? "");
  await writeFile(join(path, "user.js"), userJs, "utf8");
  return {
    path,
    async cleanup() {
      await rm(path, { recursive: true, force: true });
    },
  };
}
